// Logo image data in Base64 format
const LOGO_DATA = {
    // GHP Microfinance Logo
    base64: '/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgMDAsMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/2wBDAQMCQ4QEBQQEBQYFBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgY/wAARCAGQAZADASIAAhEBAxEB/8QAHQAAAQQDAQAAAAAAAAAAAAAABgAEBQcBAwIICf/EAEQQAAEDAwIEBAMFBwQCAwEBAAECAwQABREGEiExQVETInGBBxQjMhVSsRYjQmJx0TNDgqGxwRY0ZGOS8AhDc4Px/8QAGQEAAwEBAQAAAAAAAAAAAAAAAAECAwQF/8QAJBEBAQACAgMBAAICAwEBAAAAAAECEQMhMRJBBFEiYQUTcYH/2gAMAwEAAhEDEQA/APyfoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAK',
    
    // Alternative: You can also store as a file path
    filePath: 'logo.jpg',
    
    // MIME type
    mimeType: 'image/jpeg'
};

// Make it globally available
window.LOGO_DATA = LOGO_DATA;
